"use client"
import { LanguageProvider } from "@/context/LanguageContext";
import "./globals.css";
import Header from "./Header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          <Header />
          <div className="container">{children}</div>
        </LanguageProvider>
      </body>
    </html>
  );
}
