export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const globalStyles = `
  body {
    margin: 0;
    padding: 0;
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    gap: 100px;
  }

  #loading {
    width: 100px;
    height: 100px;
    background-color: crimson;
    border-radius: 10px;
    animation: spin 2s linear infinite;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{globalStyles}</style>
      </head>
      <body>
        <div>
          <div>Animation test</div>
          <div id="loading" />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
